DB_URL = "postgresql://neondb_owner:npg_AvzFkHQ6M3yo@ep-tiny-wind-ayd9hww0.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require"
https://clickerpy-dt2xukd7q7iqsougvfenre.streamlit.app/
ADMIN_ID = "admin"
ADMIN_PASSWORD ="admin123"
